name: CI

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  ci:
    runs-on: windows-2022
    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.203
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: microsoft
    - uses: actions/checkout@v4
    - name: Build dotnet application
      shell: pwsh
      run: |
        ./build.ps1 --target SonarQubeBegin
        ./build.ps1
        ./build.ps1 --target SonarQubeEnd
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        PROJECT_NAME: 'kostakoff_dotnet-application-template'
        SONAR_ORG: 'kostakoff'
        SONAR_HOST_URL: 'https://sonarcloud.io'
